{% set version = "0.2.0" %}

package:
  name: libxtm
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: |
    export CMAKE_PREFIX_PATH="$PREFIX"
    $PYTHON -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - python
  host:
    - python
    - pip
    - scikit-build-core
    - nanobind
    - libgdal
  run:
    - python
    - libgdal

test:
  imports:
    - xtm

about:
  home: https://github.com/yashwk/libxtm
  summary: Lossless terrain elevation compression library